### ISSUE TITLE
Unable to load 3D models view

### ISSUE THREAD

**Issue by FurryX** [willnode/WebViewHook#1]
Hi,
I've tried to show Sketchfab preview in Editor but for example https://sketchfab.com/models/1acf7ffda1b140fa8d585342ad8440e4 shows constant Loading 3D model. 
Do you know why?

Btw, great plugin! Thank you

**Comment by willnode** [comment]
I haven't test it, but it likely caused by old CEF version. 

You can open the DevTool to investigate the problem.

**Comment by FurryX** [comment]
Probably yes. Well about dev console error it shows nearly nothing, only info that some type is missing (even no info which type)

**Comment by willnode** [comment]
Just tested that website.. and it's the same.

We should have actual Chrome 37 to test whether it's actually Chrome or something else to be blamed.

**Comment by FurryX** [comment]
I've asked Unity team and they now that it doesn't work but they plan to fix this
