### ISSUE TITLE
Opening a new scene stops the WebWindow from working

### ISSUE THREAD

**Issue by Dorgam** [willnode/WebViewHook#4]
Hi,

I am using the WebWindow example in Unity 2018 and once I open a new scene the WebWindow view stops working and become grey, to make it open again, I have to close it and reopen it. Is there a fix for this to make the window persistent?

Thanks,

**Comment by Sithdown** [comment]
It also happens if you dock the WebWindow. No errors shown, just a grey window.

Any ideas?

**Comment by willnode** [comment]
Solved by 6603cc1.

Thanks for the bug report.
